# Generated by Django 5.2.5 on 2025-09-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = []
