# Generated by Django 5.2.5 on 2025-09-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="account",
            name="surname",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
