# Generated by Django 5.2.5 on 2025-09-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_account_email_account_fullname_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Account",
            new_name="Users",
        ),
    ]
