# Generated by Django 5.2.5 on 2025-09-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_account_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="surname",
            new_name="surname",
        ),
    ]
