# Generated by Django 5.2.5 on 2025-09-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_fullname_users_surname"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="users",
            unique_together={("username", "surname")},
        ),
    ]
