# Generated by Django 5.2.5 on 2025-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_users_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="users",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username", "surname"), name="unique_username_surname"
            ),
        ),
    ]
