# Generated by Django 5.2.7 on 2025-11-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_users_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
