# Generated by Django 5.2.7 on 2025-11-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_post_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
