# Generated by Django 5.2.7 on 2025-11-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
