# Generated by Django 5.2.7 on 2025-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_tag_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_username_surname",
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username",), name="unique_username_surname"
            ),
        ),
    ]
