# Generated by Django 5.2.7 on 2025-11-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_users_unique_username_surname_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_username_surname",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="surname",
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username",), name="unique_username"
            ),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("surname",), name="unique_surname"
            ),
        ),
    ]
