# Generated by Django 5.2.7 on 2025-11-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_remove_users_unique_username_surname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=550, verbose_name="Book title")),
                ("img", models.ImageField(upload_to="books/", verbose_name="Image")),
                ("body", models.TextField(verbose_name="Book body")),
                (
                    "author",
                    models.CharField(
                        default="Admin", max_length=100, verbose_name="Book author"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
