# Generated by Django 5.2.7 on 2025-11-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_book"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_surname",
        ),
    ]
