# Generated by Django 5.2.7 on 2025-11-25 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_remove_users_unique_surname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_username",
        ),
        migrations.AddField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["username"], name="blog_users_usernam_f8f33d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["surname"], name="blog_users_surname_37b2e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username", "surname"), name="unique_username_surname_together"
            ),
        ),
    ]
