# Generated by Django 5.2.7 on 2025-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_users_unique_username_users_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
