# Generated by Django 5.2.7 on 2025-11-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_users_username"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_username_surname_together",
        ),
        migrations.RemoveIndex(
            model_name="users",
            name="blog_users_usernam_f8f33d_idx",
        ),
        migrations.RemoveIndex(
            model_name="users",
            name="blog_users_surname_37b2e3_idx",
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username", "surname"),
                name="unique_username_and_surname_together",
            ),
        ),
    ]
