# Generated by Django 5.2.7 on 2025-11-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_remove_users_unique_username_surname_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_username_and_surname_together",
        ),
        migrations.RemoveField(
            model_name="users",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="book",
            name="img",
            field=models.ImageField(upload_to="", verbose_name="Image"),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username",), name="unique_username"
            ),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("surname",), name="unique_surname"
            ),
        ),
    ]
