# Generated by Django 5.2.7 on 2025-11-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_remove_users_unique_username_and_surname_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
