# Generated by Django 5.2.7 on 2025-11-25 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_delete_book"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_username",
        ),
        migrations.RemoveConstraint(
            model_name="users",
            name="unique_surname",
        ),
        migrations.AddField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.UniqueConstraint(
                fields=("username", "surname"),
                name="unique_username_and_surname_together",
            ),
        ),
    ]
