# Generated by Django 5.2.7 on 2025-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_users_managers_users_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="users",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="users",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
