# Generated by Django 5.2.7 on 2025-12-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_alter_users_managers_remove_users_date_joined_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
