# Generated by Django 6.0.3 on 2026-04-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_post_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='body',
            field=models.TextField(verbose_name='Book body'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=550, verbose_name='Book name'),
        ),
    ]
