# Generated by Django 6.0.3 on 2026-04-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_book_body_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
