# Generated by Django 6.0.5 on 2026-05-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, default='', verbose_name='Cover Image URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Economics', 'Economics'), ('Biology', 'Biology'), ('Law', 'Law'), ('Psychology', 'Psychology'), ('History', 'History'), ('Philosophy', 'Philosophy'), ('Engineering', 'Engineering'), ('Chemistry', 'Chemistry'), ('Medicine', 'Medicine'), ('General', 'General')], default='General', max_length=100, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price (BKC)'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Admin', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='body',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
    ]
