# Generated by Django 6.0.5 on 2026-05-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_book_cover_image_book_genre_book_price_book_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon', models.CharField(choices=[('warning', 'Warning'), ('stars', 'Stars'), ('mail', 'Mail'), ('info', 'Info')], default='mail', max_length=50)),
                ('color', models.CharField(choices=[('error', 'Red'), ('secondary', 'Yellow'), ('primary', 'Purple')], default='primary', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=550)),
                ('book_author', models.CharField(blank=True, max_length=200)),
                ('book_genre', models.CharField(blank=True, max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('book_img', models.URLField(blank=True, default='')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='blog.user')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
